SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[vwTIReportBase] AS (
		SELECT SEASON, CUSTOMER, CUSTOMER_TYPE, ITEM, E_PL, I_PT, I_PRICE, I_DAMT, ORDQTY, ORDTOTAL, PAIDCUSTOMER, MINPAYMENTDATE, PAIDTOTAL, INSERTDATE 
		FROM dbo.TI_ReportBase2 (NOLOCK)
			UNION ALL
		SELECT SEASON, CUSTOMER, CUSTOMER_TYPE, ITEM, E_PL, I_PT, I_PRICE, I_DAMT, ORDQTY, ORDTOTAL, PAIDCUSTOMER, MINPAYMENTDATE, PAIDTOTAL, INSERTDATE
		FROM dbo.TI_ReportBase_History (NOLOCK)
	)
GO
