SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [etl].[vw_Load_PAC_DimEvent] AS (

	SELECT  
		
		e.SEASON + ':' + e.ZID COLLATE SQL_Latin1_General_CP1_CI_AS AS ETL__SSID 
		, e.SEASON ETL__SSID_PAC_SEASON
		, e.[EVENT] ETL__SSID_PAC_EVENT

		, e.[EVENT] COLLATE SQL_Latin1_General_CP1_CI_AS EventCode
		, e.NAME COLLATE SQL_Latin1_General_CP1_CI_AS EventName
		, e.NAME + ' (' + e.EVENT COLLATE SQL_Latin1_General_CP1_CI_AS + ')' EventDesc
		, e.CLASS COLLATE SQL_Latin1_General_CP1_CI_AS EventClass
		, e.FACILITY COLLATE SQL_Latin1_General_CP1_CI_AS Arena
		, e.SEASON COLLATE SQL_Latin1_General_CP1_CI_AS Season
		, TRY_CAST(e.DATE AS DATE) EventDate
		, TRY_CAST(e.TIME AS TIME) EventTime
		, CASE 
			WHEN ISNULL(e.TIME, 'TBA') = 'TBA' THEN TRY_CAST(e.DATE AS DATETIME)
			ELSE CAST(e.DATE AS DATETIME) + TRY_CAST(e.TIME AS DATETIME) 
		END EventDateTime
		, e.ETYPE COLLATE SQL_Latin1_General_CP1_CI_AS PAC_ETYPE
		, e.BASIS COLLATE SQL_Latin1_General_CP1_CI_AS PAC_BASIS
		, e.EGROUP COLLATE SQL_Latin1_General_CP1_CI_AS PAC_EGROUP
		, e.KEYWORD COLLATE SQL_Latin1_General_CP1_CI_AS PAC_KEYWORD
		, e.TAG COLLATE SQL_Latin1_General_CP1_CI_AS PAC_TAG

	--SELECT *
	FROM dbo.TK_EVENT (NOLOCK) e

)


GO
