CREATE TABLE [dbo].[ADV_Contact]
(
[ContactID] [bigint] NOT NULL,
[ADNumber] [int] NULL,
[SetupDate] [datetime] NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ext] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatronID] [bigint] NULL,
[AlumniInfo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseBirthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseAlumniInfo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashBasisPP] [float] NULL,
[AccrualBasisPP] [float] NULL,
[AdjustedPP] [float] NULL,
[LifetimeGiving] [decimal] (18, 2) NULL,
[UserDefined1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FundraiserID] [int] NULL,
[Fundraiser] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamID] [int] NULL,
[StaffAssigned] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PPRank] [int] NULL,
[PledgeLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverrideLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiptsLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[ADV_Contact] ADD CONSTRAINT [PK_ADV_Contact] PRIMARY KEY CLUSTERED  ([ContactID])
GO
