CREATE TABLE [dbo].[TK_ODET_EVENT_ASSOC]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQ] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[EVENT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PRICE] [numeric] (18, 2) NULL,
[E_DAMT] [numeric] (18, 2) NULL,
[E_STAT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E_AQTY] [bigint] NULL,
[E_PQTY] [bigint] NULL,
[E_ADATE] [datetime] NULL,
[E_SBLS] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E_CPRICE] [numeric] (18, 2) NULL,
[E_FEE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_FPRICE] [numeric] (18, 2) NULL,
[TOT_EPAY] [numeric] (18, 2) NULL,
[TOT_CPAY] [numeric] (18, 2) NULL,
[TOT_FPAY] [numeric] (18, 2) NULL,
[E_SCAMT] [numeric] (18, 2) NULL,
[TOT_SCPAY] [numeric] (18, 2) NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
WITH
(
DATA_COMPRESSION = PAGE
)
GO
ALTER TABLE [dbo].[TK_ODET_EVENT_ASSOC] ADD CONSTRAINT [PK_TK_ODET_EVENT_ASSOC] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [CUSTOMER], [SEQ], [VMC]) WITH (DATA_COMPRESSION = PAGE)
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [dbo].[TK_ODET_EVENT_ASSOC] ([CUSTOMER]) WITH (DATA_COMPRESSION = PAGE)
GO
CREATE NONCLUSTERED INDEX [IDX_EVENT] ON [dbo].[TK_ODET_EVENT_ASSOC] ([EVENT]) WITH (DATA_COMPRESSION = PAGE)
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [dbo].[TK_ODET_EVENT_ASSOC] ([SEASON]) WITH (DATA_COMPRESSION = PAGE)
GO
CREATE NONCLUSTERED INDEX [NCIX_TK_ODET_EVENT_ASSOC_SEASON_ZID] ON [dbo].[TK_ODET_EVENT_ASSOC] ([SEASON], [ZID]) WITH (DATA_COMPRESSION = PAGE)
GO
