CREATE TABLE [stg].[TM_FactAvailSeats]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__SSID] [varchar] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_TM_ods_id] [bigint] NULL,
[ETL__SSID_TM_event_id] [int] NULL,
[ETL__SSID_TM_section_id] [int] NULL,
[ETL__SSID_TM_row_id] [int] NULL,
[ETL__SSID_TM_seat_num] [int] NULL,
[ETL__SSID_TM_price_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimDateId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTimeId] [int] NULL,
[DimArenaId] [int] NULL,
[DimSeasonId] [int] NULL,
[DimItemId] [int] NULL,
[DimEventId] [int] NULL,
[DimPlanId] [int] NULL,
[DimPriceLevelId] [int] NULL,
[DimPriceTypeId] [int] NULL,
[DimPriceCodeId] [int] NULL,
[DimSeatId_Start] [int] NULL,
[DimSeatStatusId] [int] NULL,
[DimPlanTypeId] [int] NULL,
[DimTicketTypeId] [int] NULL,
[DimSeatTypeId] [int] NULL,
[DimTicketClassId] [int] NULL,
[PostedDateTime] [datetime] NULL,
[QtySeat] [int] NULL,
[SubTotal] [decimal] (20, 6) NULL,
[Fees] [decimal] (18, 6) NULL,
[Taxes] [decimal] (18, 6) NULL,
[Total] [decimal] (18, 6) NULL,
[TM_price] [decimal] (18, 6) NULL,
[TM_block_full_price] [decimal] (18, 6) NULL,
[TM_printed_price] [decimal] (18, 6) NULL,
[TM_pc_ticket] [decimal] (18, 6) NULL,
[TM_pc_tax] [decimal] (18, 6) NULL,
[TM_pc_licfee] [decimal] (18, 6) NULL,
[TM_pc_other1] [decimal] (18, 6) NULL,
[TM_pc_other2] [decimal] (18, 6) NULL,
[TM_pc_other3] [decimal] (18, 6) NULL,
[TM_pc_other4] [decimal] (18, 6) NULL,
[TM_pc_other5] [decimal] (18, 6) NULL,
[TM_pc_other6] [decimal] (18, 6) NULL,
[TM_pc_other7] [decimal] (18, 6) NULL,
[TM_pc_other8] [decimal] (18, 6) NULL,
[TM_tax_rate_a] [decimal] (18, 6) NULL,
[TM_tax_rate_b] [decimal] (18, 6) NULL,
[TM_tax_rate_c] [decimal] (18, 6) NULL,
[TM_direction] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_quality] [int] NULL,
[TM_attribute] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_aisle] [int] NULL,
[TM_section_type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_section_sort] [int] NULL,
[TM_row_sort] [int] NULL,
[TM_row_index] [int] NULL,
[TM_block_id] [int] NULL,
[TM_config_id] [int] NULL,
[TM_plan_type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_sellable] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_onsale_datetime] [datetime] NULL,
[TM_offsale_datetime] [datetime] NULL,
[TM_block_purchase_price] [decimal] (18, 6) NULL,
[TM_sell_type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_display_status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_unsold_type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_unsold_qual_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_reserved] [bit] NULL,
[TM_oss_onsale_datetime] [datetime] NULL,
[TM_oss_offsale_datetime] [datetime] NULL,
[TM_row_barcode_index] [int] NULL,
[TM_row_barcode_index_high] [int] NULL,
[TM_barcode_season_key] [int] NULL,
[TM_barcode_event_slot_min] [int] NULL,
[TM_barcode_event_slot_max] [int] NULL,
[TM_barcode_seatcode_adjustment] [int] NULL,
[TM_access_control_system_ip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_access_control_system_port] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_seat_code_low] [int] NULL,
[TM_seat_code_high] [int] NULL,
[TM_digit_server_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_im_mode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_host_integration_enabled] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_host_synch_status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_action] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [stg].[TM_FactAvailSeats] ADD CONSTRAINT [PK__TM_FactA__C4EA244543924D8C] PRIMARY KEY CLUSTERED  ([ETL__ID])
GO
