CREATE TABLE [stg].[dbo__FactTicketSeat_V2]
(
[SaleDate] [date] NULL,
[SaleTime] [time] NULL,
[OrderDate] [date] NULL,
[PaymentDateFirst] [date] NULL,
[TicketingAccountId] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimArenaId] [int] NOT NULL,
[ArenaCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArenaName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeasonHeaderId] [int] NULL,
[SeasonHeaderCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderYear] [int] NULL,
[SeasonHeaderIsActive] [bit] NULL,
[DimSeasonId] [int] NOT NULL,
[SeasonCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonYear] [int] NULL,
[SeasonClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sport] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimEventHeaderId] [int] NULL,
[EventHeaderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDate] [date] NULL,
[EventHeaderTime] [time] NULL,
[EventHeaderDateTime] [datetime] NULL,
[EventHeaderOpenTime] [datetime] NULL,
[EventHeaderFinishTime] [datetime] NULL,
[EventSeasonNumber] [int] NULL,
[EventHeaderHomeNumber] [int] NULL,
[EventHeaderGameNumber] [int] NULL,
[EventHierarchyL1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GameType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimEventId] [int] NOT NULL,
[EventCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventDate] [date] NULL,
[EventTime] [time] NULL,
[EventDateTime] [datetime] NULL,
[EventClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAC_EGROUP] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimItemId] [int] NULL,
[ItemCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemPlanOrEvent] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPlanId] [int] NULL,
[PlanCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanFSE] [decimal] (18, 6) NULL,
[PlanType] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEventCnt] [int] NULL,
[DimPriceTypeId] [int] NULL,
[PriceTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceTypeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceTypeClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPriceLevelId] [int] NULL,
[PriceLevelCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevelName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatId] [int] NOT NULL,
[SectionName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seat] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatLocationMapping] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatLevelName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTicketClassId] [int] NULL,
[TicketClassCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketClassName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTicketTypeId] [int] NULL,
[TicketTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPlanTypeId] [int] NULL,
[PlanTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatTypeId] [int] NULL,
[SeatTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatStatusId] [int] NULL,
[SeatStatusCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatStatusName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsKill] [bit] NULL,
[DimSalesCodeId] [int] NULL,
[SalesCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesCodeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPromoId] [int] NULL,
[PromoCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSaleable] [bit] NULL,
[IsAvailable] [bit] NULL,
[IsHeld] [bit] NULL,
[IsReserved] [bit] NOT NULL,
[IsSold] [bit] NULL,
[IsComp] [bit] NOT NULL,
[IsPremium] [bit] NOT NULL,
[IsSingleEvent] [bit] NOT NULL,
[IsPlan] [bit] NOT NULL,
[IsPartial] [bit] NOT NULL,
[IsGroup] [bit] NOT NULL,
[IsRenewal] [bit] NOT NULL,
[IsBroker] [bit] NOT NULL,
[RevenueTotal] [decimal] (29, 17) NULL,
[RevenueTicket] [decimal] (29, 17) NULL,
[RevenueFees] [decimal] (29, 17) NULL,
[RevenueSurcharge] [decimal] (29, 17) NULL,
[QtySeat] [int] NOT NULL,
[PaidAmount] [decimal] (18, 6) NULL,
[OwedAmount] [decimal] (18, 6) NULL,
[IsAttended] [bit] NULL,
[ScanDateTime] [datetime] NULL,
[ScanGate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsResold] [bit] NULL,
[ResoldDateTime] [datetime] NULL,
[ResoldPurchasePrice] [decimal] (29, 17) NULL,
[ResoldFees] [decimal] (29, 17) NULL,
[ResoldTotalAmount] [decimal] (29, 17) NULL,
[ResoldDifference] [decimal] (29, 17) NULL,
[ResoldValue] [decimal] (29, 17) NULL,
[ResoldBuyer_TicketingAccountId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResoldSeller_TicketingAccountId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_PAC_EVENT] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_PAC_LEVEL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_PAC_SECTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_PAC_ROW] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_PAC_SEAT] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Config_isCapacityEligible] [bit] NULL,
[IsPair] [bit] NULL,
[CustomerId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimRepId] [int] NULL,
[FactInventoryId] [bigint] NULL,
[FactOdetId] [bigint] NULL,
[FactAttendanceId] [bigint] NULL,
[FactTicketActivityId_Resold] [bigint] NULL,
[FactTicketActivityId_Tranferred] [bigint] NULL,
[FactAvailSeatsId] [bigint] NULL,
[FactHeldSeatsId] [bigint] NULL,
[ETL__CreatedDate] [datetime] NULL CONSTRAINT [DF_dbo_FactTicketSeat_V2__ETL__CreatedDate] DEFAULT (getutcdate())
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_dbo_FactTicketSeat_V2] ON [stg].[dbo__FactTicketSeat_V2]
GO
