CREATE SCHEMA [AUDIT]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
GRANT EXECUTE ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [AUDIT] TO [db_apiETL]
GO
