CREATE SCHEMA [preODS]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [preODS] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [preODS] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [preODS] TO [db_apiETL]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [preODS] TO [db_apiETL]
GO
