CREATE SCHEMA [src]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [src] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [src] TO [db_apiETL]
GO
GRANT EXECUTE ON SCHEMA:: [src] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [src] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [src] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [src] TO [db_apiETL]
GO
